### PR TITLE
import todolist extension

### PR DESCRIPTION
**Pull request by lilic**
https://github.com/bsaleil/todolist-gnome-shell-extension

### CODE REVIEW

**Comment by iaguis** [comment]
I'd rather have one commit for the imported version and then commits for the modifications we made to make it work (e.g., whitelisting 3.8)

**Comment by iaguis** [comment]
Apart from that, it looks good and it works 👍

**Comment by lilic** [comment]
@iaguis can you have another look, thanks!

**Review by iaguis — APPROVED** [review]
lgtm

**Pull request merged**
